name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Чекаут репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List all files
      run: ls -R

    # Замена значения BITRIX_TOKEN в файле script.js
    - name: Replace BITRIX_TOKEN in script.js
      run: |
        sed -i 's/const BITRIX_TOKEN = .*/const BITRIX_TOKEN = "${{ secrets.BITRIX_TOKEN }}";/' ./script.js

    # Проверка, что замена прошла успешно
    - name: Show script.js content
      run: cat ./script.js

    # Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
