name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Чекаут репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # Использование Create a File Action для создания api_constants.js
    - name: Create api_constants.js file
      uses: AndromedaNine/create-a-file-action@v1
      with:
        path: './src/api_constants.js'  # Путь до файла
        content: "export const BITRIX_TOKEN = '${{ secrets.BITRIX_TOKEN }}';"  # Содержимое файла
        overwrite: true  # Перезаписывать файл, если он уже существует

    # Проверка, что файл api_constants.js был создан
    - name: List files in src directory
      run: ls -la ./src

    # Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
